### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by Hypothesis-github** [agentejo/CockpitQL#18]
I am new to Cockpit and I want to use this plugin in Gatsby.
please provide me with series of steps or a small example in order for me to use this plugin properly.

for example where to use 

`/api/graphql?token=*apitoken*`

where to put these 

```
{
  region(name:"test"),
  collection(name:"posts", filter:{published:true})
}
```
```

{
  allPosts(filter:{published:true}){
    _id,
    title
    content,
    image{
      path
    }
  }
}
```

should I upload this to my addon folder , and so on ...

**Comment by Hypothesis-github** [comment]
For future reference 

I used apollo-fetch in this fashion : 

```
const token = "mytoken";
const uri = `http://mydomain/cockpit/api/graphql?token=${token}`;
const apolloFetch = createApolloFetch({ uri });
const query = `{
  collection(name:"hello")
   allHello { Name }
}`;

apolloFetch({ query }).then(data => console.log(data));
```

Given that my collection name is "hello" and it is capitalized for graphQL

**Comment by praveenkumarsomu** [comment]
Hi, have you managed to integrate GraphQL in your cockpit master? I'm also facing same issue.

**Comment by Hypothesis-github** [comment]
> Hi, have you managed to integrate GraphQL in your cockpit master? I'm also facing same issue.

Can you tell me what your issue is, maybe I can help. please be specific.

**Comment by praveenkumarsomu** [comment]
I'm new to PHP I'm not sure where to add the GraphQL folder in my source, I added in the Addons folder and tried to call the http://localhost:8000/api/graphql/collections/get/DetailPage. It did not work I'm getting unauthorized.

**Comment by Hypothesis-github** [comment]
> I'm new to PHP I'm not sure where to add the GraphQL folder in my source, I added in the Addons folder and tried to call the http://localhost:8000/api/graphql/collections/get/DetailPage. It did not work I'm getting unauthorized

Are you getting unauthorized by even by using Apollo fetch ? can you send me the complete error and your piece of code ?

**Comment by praveenkumarsomu** [comment]
@Hypothesis-github I tried using the chromeiql but still getting UnAuthorised. I have not modified any CockpitQL code just added it into the Cockpit. In the below cockpit-master -> addons, please let me know if I need to modify some code.
