### ISSUE TITLE
Syntax Error GraphQL (1:2)

### ISSUE THREAD

**Issue by yarl** [agentejo/CockpitQL#3]
I want to get collection called `posts` and region called `posts_header`. I try to do it using `fetch()` function but I keep having error posted below.

Request:

```
fetch(`/api/graphql?token=${token}`, {
    body: "query { allPosts { _id, title, content } }",
    method: "POST"
})
```

Response:

```
{
  "errors": [
    {
      "message": "Syntax Error GraphQL (1:2) Expected Name, found }\n\n1: {}\n    ^\n",
      "category": "graphql",
      "locations": [
        {
          "line": 1,
          "column": 2
        }
      ]
    }
  ]
}
```

**Comment by aheinze** [comment]
maybe you should try to use a graphql js lib to do the queries.

otherwise please try:

```
fetch(`/api/graphql?token=${token}`, {
    query: "{ allPosts { _id, title, content } }",
    method: "POST"
})
```

**Comment by yarl** [comment]
Right, I used apollo-fetch and it's working like a charm 👍 

For archive happiness, here's my code.

```
const token = "...";
const uri = `/api/graphql?token=${token}`;
const apolloFetch = createApolloFetch({ uri });
const query = `{
    region(name:"posts_header"),
    collection(name:"posts", filter:{published:true})
}`;

apolloFetch({ query }).then(data => console.log(data));
```

I have one more question, though. How to query more than one region or collection using query above?

**Comment by aheinze** [comment]
you can use aliases:

```
{
    header:region(name:"posts_header", render:false),
    footer:region(name:"posts_footer", render:false),
    published:collection(name:"posts", filter:{published:true}),
    unpublished:collection(name:"posts", filter:{published:false})
}
```

**Comment by yarl** [comment]
Perfect 🙂 Last question: can I get only `data` from region using this syntax (without `fields`, `icon`, etc.)?

As a super optional thing: is it possible to do pagination of collection?

**Comment by aheinze** [comment]
regarding your first question, no sorry.

regarding your second question: yes, you can by providing additional `skip` and `limit` parameters

```
{
   collection(name:"posts", filter:{published:true}, skip:10, limit: 20),
   allPosts(skip:10, limit: 20) { _id, title, content }
}
```

**Comment by yarl** [comment]
Thanks!
