### ISSUE TITLE
Float field type would be nice to add

### ISSUE THREAD

**Issue by desperial** [agentejo/CockpitQL#34]
While working on my project, I was faced with the need to make one of the parameters a float. Unfortunately, I found out that this is not provided in the addon, which forces me to use the string field in GraphQL.

I manually added a placeholder check, but I would like to know: will this be provided in the future?

**Comment by aheinze** [comment]
Maybe this commit helps: https://github.com/agentejo/CockpitQL/commit/1a9827000702bf7f4ccb2c02b5d939d5ed7afd31

**Comment by desperial** [comment]
Yes, it helps for sure, thanks.
