### ISSUE TITLE
Lang variable does not propagate to collection links

### ISSUE THREAD

**Issue by pozylon** [agentejo/CockpitQL#36]
If you query with a lang parameter and there is a collection link, the collection link item will show up in the default language. We should be able to specify the lang on any field that returns a xyzCollectionLink type.

**Comment by aheinze** [comment]
Good point ... I think I will pass the lang parameter to collection link resolver 🤔

**Comment by aheinze** [comment]
@pozylon Could you please check the latest CockpitQL codebase if it works now? Thanks!

**Comment by pozylon** [comment]
@aheinze Danke Artur, das hilft uns immens! Will check.
