### ISSUE TITLE
No matter what i post to the api-endpoint: Internal Error

### ISSUE THREAD

**Issue by teamgroove** [agentejo/CockpitQL#4]
That is the only response i get from /api/graphql , no matter what i do. The error doesn't get more specific. Any clues, what this means?

I use the cockpit:next and this addon. Nothing fancy.

Can i have more debug messages somewhere to find the error?

**Comment by aheinze** [comment]
did you try to look into the php error log file (defined in the php.ini) ?

**Comment by teamgroove** [comment]
Ok. I'm investigating :)

**Comment by teamgroove** [comment]
There is a solid error thrown. It reads like this, but i can't interpret it very good. It can't find a Class? But the file is definately sitting there: /addons/CockpitQL-master/Types/JsonType.php
(PHP Version 7.0.28)

32304#0: *112136 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Class 'CockpitQL\Types\JsonType' not found in /var/www/vhosts/renethiel.info/api.renethiel.info/addons/CockpitQL-master/fields/region.php:10 Stack trace: #0 /var/www/vhosts/renethiel.info/api.renethiel.info/addons/CockpitQL-master/bootstrap.php(26): include() #1 /var/www/vhosts/renethiel.info/api.renethiel.info/modules/Cockpit/rest-api.php(120): LimeExtra\App->{closure}() #2 [internal function]: LimeExtra\App->{closure}(Array) #3 /var/www/vhosts/renethiel.info/api.renethiel.info/lib/Lime/App.php(1051): call_user_func(Object(Closure), Array) #4 /var/www/vhosts/renethiel.info/api.renethiel.info/lib/Lime/App.php(998): Lime\App->render_route('/api/*', Array) #5 /var/www/vhosts/renethiel.info/api.renethiel.info/lib/Lime/App.php(955): Lime\App->dispatch('/api/graphql') #6 /var/www/vhosts/renethiel.info/api.renethiel.info/index.php(37): Lime\App->run() #7 {main} thrown in /var/www/vhosts/renethiel.info/api.renethiel.info/addons/CockpitQL-master/fields/region.php o" while reading response header from upstream

**Comment by teamgroove** [comment]
Ok. I found it. It is the foldername that i used when unzipping from the downloaded git-repo of CockpitQL instead of cloning. It added "-master" to the foldername. So it was named: "addons/CockpitQL-master" instead of "addons/CockpitQL". I'm not sure if this was intended to be like that, but the foldername needs to match that cirteria. Maybe that could be mentioned in the docs.

**Comment by teamgroove** [comment]
Thank you for bringing me in the right direction! Now i can experiment with that cool new toy called CockpitQL ;)
