### ISSUE TITLE
Filter by a linked item?

### ISSUE THREAD

**Issue by scottdj92** [agentejo/CockpitQL#9]
How can I filter via a linked item?

I have a BlogPost collection that links to BlogAuthor:

```
BlogPost {
    author {
       name
    }
}
```

I would like to submit a query that's similar to:

`collection(name: "BlogPosts", filter: {author: {name: "Melissa"}},  populate: 1, sort: {publicationDate: -1})`, but I get an empty collection?

Is this possible?

**Comment by Ximore** [comment]
I would like to know this too...
